### ISSUE TITLE
FR: Show internal state of services in the robot portal

### ISSUE THREAD

**Issue by chrisvdg** [threefoldtecharchive/0-robot-portal#1]
Show internal state (service data) in the portal

**Comment by BolaNasr** [comment]
https://github.com/zero-os/0-robot-portal/pull/3

**Comment by chrisvdg** [comment]
Works!
![image](https://user-images.githubusercontent.com/23582741/45307501-7537b980-b51f-11e8-86c7-a914eabffe41.png)
